### ISSUE TITLE
[new-command-request] Ingress Health Check - Deployment ContainerPort/SVC port matching Ingress Backend port

### ISSUE THREAD

**Issue by zohebk8s** [runwhen-contrib/runwhen-local#235] opened 2023-08-04 20:45 UTC
### What do you need the command to do?

Hi Stewart,

Please find the attachment with details. Basically, it's related to an ingress health check. Whatever the commands we have in RunWhen Local are just amazing. However,
[RunWhen Local - Ingress Health Check - Commands wanted.pdf](https://github.com/runwhen-contrib/runwhen-local/files/12264544/RunWhen.Local.-.Ingress.Health.Check.-.Commands.wanted.pdf)
 I've come across a scenario and thought to share it with the community.

### Contact

Yes, please

**Comment by stewartshea** [comment] 2023-08-04 23:12
Thanks @zohebk8s -- I'll have a review next week and see if we can either improve the existing command or come up with a new one!

This is greatly appreciated!

**Comment by more-dinner** [comment] 2023-08-05 05:54
Good catch.  @jon-funk - perhaps a useful issue to raise here for some of the related tasks?

**Comment by jon-funk** [comment] 2023-08-06 05:50
Thanks @zohebk8s. The doc+example helps a ton too. I see some opportunities here for connecting this check to other troubleshooting scripts based on the kind managing the pods in question.

**Comment by stewartshea** [comment] 2023-08-07 18:47
So, this is an interesting scenario where the pod spec (managed by the deployment) and the service were not aligned, or misconfigured. While I can see the value of wanting to check that they exist, the problem is a little deeper than that. Unfortunately we can't guarantee that the pod has the `ports` field in the spec, or this field contains multiple values. 

- In the case the `ports` field doesn't exist, the container image itself still can have a port open we have no value to check against when querying the pod or deployment. In many of the implementations I've done, the `ports` field is never used. 

- In the case where this exists, but there are multiple values, we could check that at least one of them exists in the service configuration, but this again could continue to be misleading if the wrong port is selected. 

I could see a version of this where we can check if the details are missing or appear mismatched and ask the user to go deeper into those resources, but it's only a pointer and not a guarantee. The other option is to show all ports configured on the deployment  - but in many cases there won't be any information here.

**Comment by zohebk8s** [comment] 2023-08-08 16:10
If you feel it’s quite complex & complicated with no real possibility of getting the details, feel free to close this issue.

Asking user or displaying ports configured in deployment is really a great idea. Whatever you feel best, you can add.

Thank you for spending time on this.

**Comment by stewartshea** [comment] 2023-08-23 15:07
https://github.com/runwhen-contrib/rw-cli-codecollection/pull/189 adds some logic to detect mismatches where possible. Note that just because the conatinerPort is set in the spec, doesn't mean that it is the port the app is running on, but hopefully this adds additional detail where possible.

**Comment by stewartshea** [comment] 2023-08-23 16:47
I added some more discussion content here: https://github.com/orgs/runwhen-contrib/discussions/219#discussioncomment-6804236

I suspect we can close the issue now that we surface up some of this detail, along with continuing the discussion in the link above.

**Closed by stewartshea** 2023-08-23 16:47 UTC
Labels: new-command-request
