### ISSUE TITLE
[runwhen-local-feedback] Can't live update workspaceInfo.yaml

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#347] opened 2023-10-12 15:11 UTC
**Observation** 
If we update workspaceInfo.yaml and re-run discovery, it looks like the changes in workspaceInfo.yaml are not reflected. I've tested this with a custom codecollection, changed the ref, and rerun discovery - noticing that the configuration doesn't appear to be updated.

The only way to get the changes to take effect is to restart the container/pod.  

**Possible Suggestions**

**Any other details or context**

**Comment by vaterlaus** [comment] 2023-10-23 20:31
I think this is probably related to something in the code collection caching code, not in the reloading of workspaceInfo. Each invocation of the run.py tool always loads the workspaceInfo from the file system and doesn't cache anything, so it's not clear to me how it wouldn't pick up changes unless there's some caching going on with the shared volume between the RWL container and the host system, which I don't think is the case, right? I'm guessing if you changed some other non-code-collection-related setting in workspaceInfo you would see that reflected in the generated output.

Anyway, i can do some debugging to see if I can reproduce the problem with changing to a different ref for a given code collection repo. Also, just to double-check, since this is a somewhat older bug, this was happening for you with a build that had my fix for a previous code collection caching bug, right?

**Comment by vaterlaus** [comment] 2024-01-10 16:46
I spent some time trying to reproduce this and wasn't able to. The things I tried were:

- switching to a different branch in the same code collection specified in the workspace info
- adding a new commit to the existing branch specified in the workspace info

Both of these were after first executing the workspace builder once, so it would have already cloned the code collection repo and cached any info. But in both cases the subsequent execution of the workspace builder correctly picked up the change to the ref/branch in the code collection. So I'm not sure if there's some other case that Shea was trying that didn't work that I didn't try, so I'm going to reassign back to him. I do know that there was a bug with how the workspace builder was fetching new commits to branches that I fixed a while back, so it's possible that this ticket predates that fix, and it's not a problem anymore.

**Closed** 2024-02-29 16:42 UTC
Labels: bug
